plugins {
  id 'java'
  id 'application'
  id 'org.javamodularity.moduleplugin' version '1.8.12'
  id 'org.openjfx.javafxplugin' version '0.0.13'
  id 'org.beryx.jlink' version '2.25.0'
}

group 'org.foxprod'
version '0.4'

repositories {
  mavenCentral()
}

ext {
  junitVersion = '5.10.2'
}

sourceCompatibility = '21'
targetCompatibility = '21'

tasks.withType(JavaCompile) {
  options.encoding = 'UTF-8'
}

application {
  mainModule = 'org.foxprod.com_grapher'
  mainClass = 'org.foxprod.com_grapher.MainApplication'
}

javafx {
  version = '21'
  modules = ['javafx.controls', 'javafx.fxml']
}

jlink {
  targetPlatform("win") {
  }
  options = ['--strip-debug', '--no-header-files', '--no-man-pages']
  launcher{
    name = 'COM_Grapher'
    jvmArgs = ['-Dlog4j.configurationFile=./log4j2.xml']
  }
}

dependencies {
  implementation('org.controlsfx:controlsfx:11.2.1')
  implementation("com.fazecast:jSerialComm:[2.0.0,3.0.0)")
  testImplementation("org.junit.jupiter:junit-jupiter-api:${junitVersion}")
  testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:${junitVersion}")
}

test {
useJUnitPlatform()}


jlinkZip {
  group = 'distribution'
}
